<a href="https://colab.research.google.com/github/prithvee2k4/B13-DSA-CS2/blob/main/CS2_Prithvi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
#TASK 1
import pandas as pd

population_path = "/content/drive/MyDrive/DSAB13/CaseStudy/CS1/population.csv"

population_df = pd.read_csv(population_path)

print("First 5 rows:")
display(population_df.head())

print("Shape:")
print(population_df.shape)

print("Data Types:")
print(population_df.dtypes)

#PART B- To explore datasets.

population_df.shape[0]

First 5 rows:

         country  population
0  United States   331002651
1          China  1411778724
2          India  1380004385
3          Japan   125836021
4        Germany    83240525

Shape:
(25, 2)
Data Types:
country       object
population     int64
dtype: object

25

In [ ]:
#TASK 1
import pandas as pd

population_path = "/content/drive/MyDrive/DSAB13/CaseStudy/population.csv"

population_df = pd.read_csv(population_path)

print("First 5 rows:")
display(population_df.head())
print("\n")

print("Shape:")
print(population_df.shape)
print("\n")

print("Data Types:")
print(population_df.dtypes)
print("\n")

#PART B- To explore datasets.

print("No : of rows:")
print(population_df.shape[0]) #No : of rows
print("\n")

print("No : of columns:")
print(population_df.shape[1]) #No : of columns
print("\n")

print("Column Names:")
print(population_df.columns) #Column Names
print("\n")

print("Data Types:")
print(population_df.dtypes) #Data Types
print("\n")

print("Missing Values:")
print(population_df.isnull().sum()) #Missing Values
print("\n")

print("Duplicate records")
print(population_df.duplicated().sum()) #Duplicate records
print("\n")

First 5 rows:

         country  population
0  United States   331002651
1          China  1411778724
2          India  1380004385
3          Japan   125836021
4        Germany    83240525

Shape:
(25, 2)


Data Types:
country       object
population     int64
dtype: object


No : of rows:
25


No : of columns:
2


Column Names:
Index(['country', 'population'], dtype='object')


Data Types:
country       object
population     int64
dtype: object


Missing Values:
country       0
population    0
dtype: int64


Duplicate records
0

In [9]:
#TASK 2
import pandas as pd

gdp_path = "/content/drive/MyDrive/DSAB13/CaseStudy/CS1/gdp.xlsx"

gdp_df = pd.read_excel(gdp_path)

print("Column Names:")
print(gdp_df.columns)

print("\n")

print("Data Types:")
print(gdp_df.dtypes)

#PART B- To explore datasets.

print("No : of rows:")
print(gdp_df.shape[0]) #No : of rows
print("\n")

print("No : of columns:")
print(gdp_df.shape[1]) #No : of columns
print("\n")

print("Column Names:")
print(gdp_df.columns) #Column Names
print("\n")

print("Data Types:")
print(gdp_df.dtypes) #Data Types
print("\n")

print("Missing Values:")
print(gdp_df.isnull().sum()) #Missing Values
print("\n")

print("Duplicate records")
print(gdp_df.duplicated().sum()) #Duplicate records
print("\n")

Column Names:
Index(['Country', 'GDP'], dtype='object')


Data Types:
Country    object
GDP         int64
dtype: object
No : of rows:
25


No : of columns:
2


Column Names:
Index(['Country', 'GDP'], dtype='object')


Data Types:
Country    object
GDP         int64
dtype: object


Missing Values:
Country    0
GDP        0
dtype: int64


Duplicate records
0

In [10]:
#TASK 3
import pandas as pd

internet_users_path = "/content/drive/MyDrive/DSAB13/CaseStudy/CS1/internet_users.json"

internet_users_df = pd.read_json(internet_users_path) #converted json data to df.

print("Internet Users Dataset:")
display(internet_users_df)
print("\n")

#PART B- To explore datasets.

print("No : of rows:")
print(internet_users_df.shape[0]) #No : of rows
print("\n")

print("No : of columns:")
print(internet_users_df.shape[1]) #No : of columns
print("\n")

print("Column Names:")
print(internet_users_df.columns) #Column Names
print("\n")

print("Data Types:")
print(internet_users_df.dtypes) #Data Types
print("\n")

print("Missing Values:")
print(internet_users_df.isnull().sum()) #Missing Values
print("\n")

print("Duplicate records")
print(internet_users_df.duplicated().sum()) #Duplicate records
print("\n")

Internet Users Dataset:

           country  internet_users
0    United States       312000000
1            China      1080000000
2            India       850000000
3            Japan       118000000
4          Germany        79000000
5   United Kingdom        66000000
6           France        62000000
7            Italy        56000000
8           Canada        36000000
9        Australia        24000000
10          Brazil       181000000
11          Russia       125000000
12     South Korea        50000000
13           Spain        44000000
14          Mexico       102000000
15       Indonesia       212000000
16    Saudi Arabia        34000000
17          Turkey        69000000
18    South Africa        43000000
19       Argentina        41000000
20     Netherlands        17000000
21     Switzerland         8500000
22          Sweden        10100000
23          Norway         5300000
24       Singapore         5600000

No : of rows:
25


No : of columns:
2


Column Names:
Index(['country', 'internet_users'], dtype='object')


Data Types:
country           object
internet_users     int64
dtype: object


Missing Values:
country           0
internet_users    0
dtype: int64


Duplicate records
0

In [4]:
literacy_date_path = "/content/drive/MyDrive/DSAB13/CaseStudy/CS1/literacy_rate.xml"

with open(literacy_date_path, "r", encoding="utf-8") as file:
    print(file.read()[:1000])

<?xml version='1.0' encoding='utf-8'?>
<data><country name="United States"><literacy_rate>99.0</literacy_rate></country><country name="China"><literacy_rate>97.2</literacy_rate></country><country name="India"><literacy_rate>77.7</literacy_rate></country><country name="Japan"><literacy_rate>99.0</literacy_rate></country><country name="Germany"><literacy_rate>99.0</literacy_rate></country><country name="United Kingdom"><literacy_rate>99.0</literacy_rate></country><country name="France"><literacy_rate>99.0</literacy_rate></country><country name="Italy"><literacy_rate>99.0</literacy_rate></country><country name="Canada"><literacy_rate>99.0</literacy_rate></country><country name="Australia"><literacy_rate>99.0</literacy_rate></country><country name="Brazil"><literacy_rate>93.2</literacy_rate></country><country name="Russia"><literacy_rate>99.7</literacy_rate></country><country name="South Korea"><literacy_rate>98.8</literacy_rate></country><country name="Spain"><literacy_rate>98.6</literacy

In [5]:
import pandas as pd

literacy_date_path = "/content/drive/MyDrive/DSAB13/CaseStudy/CS1/literacy_rate.xml"

literacy_date_df = pd.read_xml(literacy_date_path)

print("Literacy Rate Dataset:")
display(literacy_date_df)
print("\n")

print("First 5 rows:")
display(literacy_date_df.head())
print("\n")

print("\nColumn Names:")
print(literacy_date_df.columns)
print("\n")

print("\nData Types:")
print(literacy_date_df.dtypes)
print("\n")

#PART B- TASK 5: To explore datasets.

print("No : of rows:")
print(literacy_date_df.shape[0]) #No : of rows
print("\n")

print("No : of columns:")
print(literacy_date_df.shape[1]) #No : of columns
print("\n")

print("Column Names:")
print(literacy_date_df.columns) #Column Names
print("\n")

print("Data Types:")
print(literacy_date_df.dtypes) #Data Types
print("\n")

print("Missing Values:")
print(literacy_date_df.isnull().sum()) #Missing Values
print("\n")

print("Duplicate records")
print(literacy_date_df.duplicated().sum()) #Duplicate records
print("\n")

Literacy Rate Dataset:

              name  literacy_rate
0    United States           99.0
1            China           97.2
2            India           77.7
3            Japan           99.0
4          Germany           99.0
5   United Kingdom           99.0
6           France           99.0
7            Italy           99.0
8           Canada           99.0
9        Australia           99.0
10          Brazil           93.2
11          Russia           99.7
12     South Korea           98.8
13           Spain           98.6
14          Mexico           95.4
15       Indonesia           96.0
16    Saudi Arabia           97.3
17          Turkey           96.7
18    South Africa           95.0
19       Argentina           99.1
20     Netherlands           99.0
21     Switzerland           99.0
22          Sweden           99.0
23          Norway          100.0
24       Singapore           97.5

First 5 rows:

            name  literacy_rate
0  United States           99.0
1          China           97.2
2          India           77.7
3          Japan           99.0
4        Germany           99.0

Column Names:
Index(['name', 'literacy_rate'], dtype='object')



Data Types:
name              object
literacy_rate    float64
dtype: object


No : of rows:
25


No : of columns:
2


Column Names:
Index(['name', 'literacy_rate'], dtype='object')


Data Types:
name              object
literacy_rate    float64
dtype: object


Missing Values:
name             0
literacy_rate    0
dtype: int64


Duplicate records
0

In [11]:
#TASK 6
# To fetch and check column names

print("Population columns:")
print(population_df.columns)

print("\nGDP columns:")
print(gdp_df.columns)

print("\nInternet Users columns:")
print(internet_users_df.columns)

print("\nLiteracy Rate columns:")
print(literacy_date_df.columns)

Population columns:
Index(['country', 'population'], dtype='object')

GDP columns:
Index(['Country', 'GDP'], dtype='object')

Internet Users columns:
Index(['country', 'internet_users'], dtype='object')

Literacy Rate columns:
Index(['name', 'literacy_rate'], dtype='object')

In [13]:
# Rename only 2 columns.
gdp_df.rename(columns={'Country': 'country'}, inplace=True)

literacy_date_df.rename(columns={'name': 'country'}, inplace=True)

# To verify
print(population_df.columns)
print(gdp_df.columns)
print(internet_users_df.columns)
print(literacy_date_df.columns)

Index(['country', 'population'], dtype='object')
Index(['country', 'GDP'], dtype='object')
Index(['country', 'internet_users'], dtype='object')
Index(['country', 'literacy_rate'], dtype='object')

In [15]:
# TASK 7
# Check datatypes
print("Population:")
print(population_df.dtypes)

print("\nGDP:")
print(gdp_df.dtypes)

print("\nInternet Users:")
print(internet_users_df.dtypes)

print("\nLiteracy Rate:")
print(literacy_date_df.dtypes)


print("\n")

#To change to appropriate datatypes

population_df['population'] = pd.to_numeric(population_df['population'])
gdp_df['GDP'] = pd.to_numeric(gdp_df['GDP'])
internet_users_df['internet_users'] = pd.to_numeric(internet_users_df['internet_users'])
literacy_date_df['literacy_rate'] = pd.to_numeric(literacy_date_df['literacy_rate'])

Population:
country       object
population     int64
dtype: object

GDP:
country    object
GDP         int64
dtype: object

Internet Users:
country           object
internet_users     int64
dtype: object

Literacy Rate:
country           object
literacy_rate    float64
dtype: object

In [18]:
# TASK 8
# to merge all 4 datasets into 1 df. named = 'merged_df'

merged_df = pd.merge(population_df, gdp_df, on='country')
merged_df = pd.merge(merged_df, internet_users_df, on='country')
merged_df = pd.merge(merged_df, literacy_date_df, on='country')

# To display
print(merged_df)

           country  population       GDP  internet_users  literacy_rate
0    United States   331002651  30500000       312000000           99.0
1            China  1411778724  19230000      1080000000           97.2
2            India  1380004385   4187000       850000000           77.7
3            Japan   125836021   4180000       118000000           99.0
4          Germany    83240525   4744000        79000000           99.0
5   United Kingdom    67886011   3839000        66000000           99.0
6           France    65273511   3211000        62000000           99.0
7            Italy    60461826   2420000        56000000           99.0
8           Canada    38005238   2250000        36000000           99.0
9        Australia    25687041   1880000        24000000           99.0
10          Brazil   212559417   2330000       181000000           93.2
11          Russia   145934462   2200000       125000000           99.7
12     South Korea    51780579   1800000        50000000           98.8
13           Spain    46754778   1710000        44000000           98.6
14          Mexico   128932753   1810000       102000000           95.4
15       Indonesia   273523615   1500000       212000000           96.0
16    Saudi Arabia    34813871   1100000        34000000           97.3
17          Turkey    84339067   1350000        69000000           96.7
18    South Africa    59308690    410000        43000000           95.0
19       Argentina    45195774    640000        41000000           99.1
20     Netherlands    17441139   1150000        17000000           99.0
21     Switzerland     8654622    940000         8500000           99.0
22          Sweden    10353442    650000        10100000           99.0
23          Norway     5421241    580000         5300000          100.0
24       Singapore     5850342    530000         5600000           97.5

In [26]:
# TASK 9
# 1. Internet Penetration (%)
# The formula is:
# Internet Penetration = (Internet Users / Population) × 100
merged_df['Internet Penetration (%)'] = (
    merged_df['internet_users'] / merged_df['population'] * 100
).round(2)

# 2. GDP Per Capital
# The formula is:
# GDP Per Capita = GDP / Population

merged_df['GDP Per Capital'] = (
    merged_df['GDP'] * 1000000 / merged_df['population']
).round(2)

# To display the merged_df

display(merged_df)

,country,population,GDP,internet_users,literacy_rate,Internet Penetration (%),GDP Per Capital,GDP Per Capita
0,United States,331002651,30500000,312000000,99.0,94.26,92144.28,92144.28
1,China,1411778724,19230000,1080000000,97.2,76.50,13621.11,13621.11
2,India,1380004385,4187000,850000000,77.7,61.59,3034.05,3034.05
3,Japan,125836021,4180000,118000000,99.0,93.77,33217.83,33217.83
4,Germany,83240525,4744000,79000000,99.0,94.91,56991.47,56991.47
5,United Kingdom,67886011,3839000,66000000,99.0,97.22,56550.68,56550.68
6,France,65273511,3211000,62000000,99.0,94.98,49193.00,49193.00
7,Italy,60461826,2420000,56000000,99.0,92.62,40025.25,40025.25
8,Canada,38005238,2250000,36000000,99.0,94.72,59202.37,59202.37
9,Australia,25687041,1880000,24000000,99.0,93.43,73188.66,73188.66
10,Brazil,212559417,2330000,181000000,93.2,85.15,10961.64,10961.64
11,Russia,145934462,2200000,125000000,99.7,85.65,15075.26,15075.26
12,South Korea,51780579,1800000,50000000,98.8,96.56,34762.07,34762.07
13,Spain,46754778,1710000,44000000,98.6,94.11,36573.80,36573.80
14,Mexico,128932753,1810000,102000000,95.4,79.11,14038.33,14038.33
15,Indonesia,273523615,1500000,212000000,96.0,77.51,5483.99,5483.99
16,Saudi Arabia,34813871,1100000,34000000,97.3,97.66,31596.60,31596.60
17,Turkey,84339067,1350000,69000000,96.7,81.81,16006.82,16006.82
18,South Africa,59308690,410000,43000000,95.0,72.50,6912.98,6912.98
19,Argentina,45195774,640000,41000000,99.1,90.72,14160.62,14160.62
20,Netherlands,17441139,1150000,17000000,99.0,97.47,65936.06,65936.06
21,Switzerland,8654622,940000,8500000,99.0,98.21,108612.48,108612.48
22,Sweden,10353442,650000,10100000,99.0,97.55,62781.05,62781.05
23,Norway,5421241,580000,5300000,100.0,97.76,106986.57,106986.57
24,Singapore,5850342,530000,5600000,97.5,95.72,90592.99,90592.99

In [27]:
#PART D
#TASK 10

import sqlite3

# Create SQLite database
conn = sqlite3.connect("country_statistics.db")

# Store DataFrame in SQLite table
merged_df.to_sql("country_statistics", conn, if_exists="replace", index=False)

print("Data successfully stored in country_statistics table.")

# Checking whether the data was stored in table country_statistics

result = pd.read_sql("SELECT * FROM country_statistics", conn)

display(result)

Data successfully stored in country_statistics table.

,country,population,GDP,internet_users,literacy_rate,Internet Penetration (%),GDP Per Capital,GDP Per Capita
0,United States,331002651,30500000,312000000,99.0,94.26,92144.28,92144.28
1,China,1411778724,19230000,1080000000,97.2,76.50,13621.11,13621.11
2,India,1380004385,4187000,850000000,77.7,61.59,3034.05,3034.05
3,Japan,125836021,4180000,118000000,99.0,93.77,33217.83,33217.83
4,Germany,83240525,4744000,79000000,99.0,94.91,56991.47,56991.47
5,United Kingdom,67886011,3839000,66000000,99.0,97.22,56550.68,56550.68
6,France,65273511,3211000,62000000,99.0,94.98,49193.00,49193.00
7,Italy,60461826,2420000,56000000,99.0,92.62,40025.25,40025.25
8,Canada,38005238,2250000,36000000,99.0,94.72,59202.37,59202.37
9,Australia,25687041,1880000,24000000,99.0,93.43,73188.66,73188.66
10,Brazil,212559417,2330000,181000000,93.2,85.15,10961.64,10961.64
11,Russia,145934462,2200000,125000000,99.7,85.65,15075.26,15075.26
12,South Korea,51780579,1800000,50000000,98.8,96.56,34762.07,34762.07
13,Spain,46754778,1710000,44000000,98.6,94.11,36573.80,36573.80
14,Mexico,128932753,1810000,102000000,95.4,79.11,14038.33,14038.33
15,Indonesia,273523615,1500000,212000000,96.0,77.51,5483.99,5483.99
16,Saudi Arabia,34813871,1100000,34000000,97.3,97.66,31596.60,31596.60
17,Turkey,84339067,1350000,69000000,96.7,81.81,16006.82,16006.82
18,South Africa,59308690,410000,43000000,95.0,72.50,6912.98,6912.98
19,Argentina,45195774,640000,41000000,99.1,90.72,14160.62,14160.62
20,Netherlands,17441139,1150000,17000000,99.0,97.47,65936.06,65936.06
21,Switzerland,8654622,940000,8500000,99.0,98.21,108612.48,108612.48
22,Sweden,10353442,650000,10100000,99.0,97.55,62781.05,62781.05
23,Norway,5421241,580000,5300000,100.0,97.76,106986.57,106986.57
24,Singapore,5850342,530000,5600000,97.5,95.72,90592.99,90592.99

In [28]:
# TASK 11
# To Retrieve the first five records from the SQLite table.

query = "SELECT * FROM country_statistics LIMIT 5"

result = pd.read_sql(query, conn)

display(result)

,country,population,GDP,internet_users,literacy_rate,Internet Penetration (%),GDP Per Capital,GDP Per Capita
0,United States,331002651,30500000,312000000,99.0,94.26,92144.28,92144.28
1,China,1411778724,19230000,1080000000,97.2,76.50,13621.11,13621.11
2,India,1380004385,4187000,850000000,77.7,61.59,3034.05,3034.05
3,Japan,125836021,4180000,118000000,99.0,93.77,33217.83,33217.83
4,Germany,83240525,4744000,79000000,99.0,94.91,56991.47,56991.47

In [29]:
# PART E

# 1. Top 5 countries by GDP
print("1. Top 5 Countries by GDP")
display(merged_df.nlargest(5, 'GDP')[['country', 'GDP']])
print("\n")

# 2. Top 5 countries by population
print("2. Top 5 Countries by Population")
display(merged_df.nlargest(5, 'population')[['country', 'population']])
print("\n")

# 3. Average literacy rate
print("3. Average Literacy Rate:")
print(round(merged_df['literacy_rate'].mean(), 2))
print("\n")

# 4. Literacy rate greater than 90%
print("\n4. Countries with Literacy Rate > 90%")
display(merged_df[merged_df['literacy_rate'] > 90][['country', 'literacy_rate']])
print("\n")

# 5. Internet penetration greater than 70%
print("\n5. Countries with Internet Penetration > 70%")
display(merged_df[merged_df['Internet Penetration (%)'] > 70][['country', 'Internet Penetration (%)']])
print("\n")

# 6. Top 5 countries by GDP per capita
print("\n6. Top 5 Countries by GDP Per Capital")
display(merged_df.nlargest(5, 'GDP Per Capital')[['country', 'GDP Per Capita']])
print("\n")

# 7. Total population
print("\n7. Total Population:")
print(merged_df['population'].sum())
print("\n")

# 8. Average internet penetration
print("\n8. Average Internet Penetration:")
print(round(merged_df['Internet Penetration (%)'].mean(), 2))
print("\n")

# 9. Highest number of internet users
print("\n9. Country with Highest Internet Users:")
display(merged_df.loc[merged_df['internet_users'].idxmax(), ['country', 'internet_users']])
print("\n")

# 10. Correlation
print("\n10. Correlation between Literacy Rate and Internet Penetration:")
print(round(merged_df['literacy_rate'].corr(merged_df['Internet Penetration (%)']), 2))
print("\n")

1. Top 5 Countries by GDP

         country       GDP
0  United States  30500000
1          China  19230000
4        Germany   4744000
2          India   4187000
3          Japan   4180000

2. Top 5 Countries by Population

          country  population
1           China  1411778724
2           India  1380004385
0   United States   331002651
15      Indonesia   273523615
10         Brazil   212559417

3. Average Literacy Rate:
97.25



4. Countries with Literacy Rate > 90%

           country  literacy_rate
0    United States           99.0
1            China           97.2
3            Japan           99.0
4          Germany           99.0
5   United Kingdom           99.0
6           France           99.0
7            Italy           99.0
8           Canada           99.0
9        Australia           99.0
10          Brazil           93.2
11          Russia           99.7
12     South Korea           98.8
13           Spain           98.6
14          Mexico           95.4
15       Indonesia           96.0
16    Saudi Arabia           97.3
17          Turkey           96.7
18    South Africa           95.0
19       Argentina           99.1
20     Netherlands           99.0
21     Switzerland           99.0
22          Sweden           99.0
23          Norway          100.0
24       Singapore           97.5

5. Countries with Internet Penetration > 70%

           country  Internet Penetration (%)
0    United States                     94.26
1            China                     76.50
3            Japan                     93.77
4          Germany                     94.91
5   United Kingdom                     97.22
6           France                     94.98
7            Italy                     92.62
8           Canada                     94.72
9        Australia                     93.43
10          Brazil                     85.15
11          Russia                     85.65
12     South Korea                     96.56
13           Spain                     94.11
14          Mexico                     79.11
15       Indonesia                     77.51
16    Saudi Arabia                     97.66
17          Turkey                     81.81
18    South Africa                     72.50
19       Argentina                     90.72
20     Netherlands                     97.47
21     Switzerland                     98.21
22          Sweden                     97.55
23          Norway                     97.76
24       Singapore                     95.72

6. Top 5 Countries by GDP Per Capital

          country  GDP Per Capita
21    Switzerland       108612.48
23         Norway       106986.57
0   United States        92144.28
24      Singapore        90592.99
9       Australia        73188.66

7. Total Population:
4720039725



8. Average Internet Penetration:
89.66



9. Country with Highest Internet Users:

country                China
internet_users    1080000000
Name: 1, dtype: object

10. Correlation between Literacy Rate and Internet Penetration:
0.77

In [36]:
import pandas as pd
import sqlite3

conn = sqlite3.connect("countries.db")

merged_df.to_sql("countries", conn, if_exists="replace", index=False)

# OP gives: 25 rows were written into the SQLite table

25

In [39]:
# Q11 - Display the Top 5 countries by GDP
q11 = """
SELECT country, GDP
FROM countries
ORDER BY GDP DESC
LIMIT 5;
"""

print("Q11 - Top 5 Countries by GDP")
display(pd.read_sql_query(q11, conn))
print("\n")


# Q12 - Find the average literacy rate
q12 = """
SELECT AVG(literacy_rate) AS Average_Literacy_Rate
FROM countries;
"""

print("Q12 - Average Literacy Rate")
display(pd.read_sql_query(q12, conn))
print("\n")


# Q13 - Display all countries having literacy rate above 90%
q13 = """
SELECT country, literacy_rate
FROM countries
WHERE literacy_rate > 90;
"""

print("Q13 - Countries with Literacy Rate Above 90%")
display(pd.read_sql_query(q13, conn))
print("\n")


# Q14 - Find the Top 5 countries with the highest internet penetration
q14 = """
SELECT country, "Internet Penetration (%)"
FROM countries
ORDER BY "Internet Penetration (%)" DESC
LIMIT 5;
"""

print("Q14 - Top 5 Countries by Internet Penetration")
display(pd.read_sql_query(q14, conn))
print("\n")


# Q15 - Calculate the total population
q15 = """
SELECT SUM(population) AS Total_Population
FROM countries;
"""

print("Q15 - Total Population")
display(pd.read_sql_query(q15, conn))
print("\n")


# Q16 - Find the country with the highest GDP per capita
q16 = """
SELECT country, "GDP Per Capita"
FROM countries
ORDER BY "GDP Per Capita" DESC
LIMIT 1;
"""

print("Q16 - Country with Highest GDP Per Capita")
display(pd.read_sql_query(q16, conn))
print("\n")


# Q17 - Export the final merged dataset as a CSV file
final_df = pd.read_sql_query("SELECT * FROM countries", conn)

final_df.to_csv("final_merged_dataset.csv", index=False)

print("Q17 - Final merged dataset exported successfully")
print("\n")


# Q18 - Sort the dataset in descending order of GDP Per Capita
# and display the Top 10 countries
q18 = """
SELECT country, "GDP Per Capita"
FROM countries
ORDER BY "GDP Per Capita" DESC
LIMIT 10;
"""

print("Q18 - Top 10 Countries by GDP Per Capita")
display(pd.read_sql_query(q18, conn))
print("\n")

Q11 - Top 5 Countries by GDP

         country       GDP
0  United States  30500000
1          China  19230000
2        Germany   4744000
3          India   4187000
4          Japan   4180000

Q12 - Average Literacy Rate

   Average_Literacy_Rate
0                 97.248

Q13 - Countries with Literacy Rate Above 90%

           country  literacy_rate
0    United States           99.0
1            China           97.2
2            Japan           99.0
3          Germany           99.0
4   United Kingdom           99.0
5           France           99.0
6            Italy           99.0
7           Canada           99.0
8        Australia           99.0
9           Brazil           93.2
10          Russia           99.7
11     South Korea           98.8
12           Spain           98.6
13          Mexico           95.4
14       Indonesia           96.0
15    Saudi Arabia           97.3
16          Turkey           96.7
17    South Africa           95.0
18       Argentina           99.1
19     Netherlands           99.0
20     Switzerland           99.0
21          Sweden           99.0
22          Norway          100.0
23       Singapore           97.5

Q14 - Top 5 Countries by Internet Penetration

        country  Internet Penetration (%)
0   Switzerland                     98.21
1        Norway                     97.76
2  Saudi Arabia                     97.66
3        Sweden                     97.55
4   Netherlands                     97.47

Q15 - Total Population

   Total_Population
0        4720039725

Q16 - Country with Highest GDP Per Capita

       country  GDP Per Capita
0  Switzerland       108612.48

Q17 - Final merged dataset exported successfully


Q18 - Top 10 Countries by GDP Per Capita

          country  GDP Per Capita
0     Switzerland       108612.48
1          Norway       106986.57
2   United States        92144.28
3       Singapore        90592.99
4       Australia        73188.66
5     Netherlands        65936.06
6          Sweden        62781.05
7          Canada        59202.37
8         Germany        56991.47
9  United Kingdom        56550.68